### ISSUE TITLE
使用说明指向github中的地址，无法打开

### ISSUE THREAD

**Issue by slslll** [GalensGan/SendMultipleEmails#10]
![Snipaste_2022-04-08_08-38-12](https://user-images.githubusercontent.com/38198381/162343532-79754967-4c8d-41b0-a9b3-2db1f6812436.png)

**Comment by GalensGan** [comment]
尴尬了，我上次修改了说明链接，没有及时更新，可以直接访问：[单击跳转使用说明](https://galens.uamazing.cn/posts/2020/2QMK677.html) 查看

**Comment by GalensGan** [comment]
已修复 05e4206107e65f986713f523ce81b6b07d19d9a9

**Comment by slslll** [comment]
发现这里还有一个，嘿嘿我是不是太闲了
![Snipaste_2022-04-08_09-58-57](https://user-images.githubusercontent.com/38198381/162348237-044718e6-4efe-4155-ab50-321570bd4551.png)

**Comment by GalensGan** [comment]
哈哈，专业！下个版本再更新吧。

**Comment by GalensGan** [comment]
[新版本](https://github.com/GalensGan/SendMultipleEmails/releases)已经更新了
