### ISSUE TITLE
可以把端口和安全连接做成UI可配置项

### ISSUE THREAD

**Issue by hhrhzy** [GalensGan/SendMultipleEmails#12]
你好
 // 开始并行发送
                    //确定smtp服务器地址 实例化一个Smtp客户端
                    SmtpClient smtpclient = new SmtpClient();
                    smtpclient.Host = _sendBox.smtp;
                    //smtpClient.Port = "";//qq邮箱可以不用端口
                    //邮件发送方式  通过网络发送到smtp服务器
                    smtpclient.DeliveryMethod = SmtpDeliveryMethod.Network;
                    //如果服务器支持安全连接，则将安全连接设为true
                    smtpclient.EnableSsl = true;

这个地方很多邮箱得指定端口，或者安全链接设置，可以把端口和安全连接做成可配置项

**Comment by GalensGan** [comment]
谢谢你的建议，我抽空优化下

**Comment by GalensGan** [comment]
你好，非常感谢您的反馈，已经优化完毕了，详见 [新版本](https://github.com/GalensGan/SendMultipleEmails/releases)
