### ISSUE TITLE
是否可以把发送间隔自定义？

### ISSUE THREAD

**Issue by JusufUs** [GalensGan/SendMultipleEmails#13]
作者您好，很不错的产品，我想提交个建议：
用自己的企业邮箱作为唯一发件人的时候，间隔最大只能设置为20-20，这样间隔时间太小会影响到达率

**Comment by GalensGan** [comment]
谢谢建议！项目正在进行重构，最近比较忙，进度有点慢~

**Comment by GalensGan** [comment]
[新版本](https://github.com/GalensGan/SendMultipleEmails/releases) 新版本已经支持自由设置了
