### ISSUE TITLE
导入收件人空白

### ISSUE THREAD

**Issue by tradingeva** [GalensGan/SendMultipleEmails#17]
使用从excel导入收件人邮箱会出现空白 请问是什么问题呢？
![image](https://user-images.githubusercontent.com/115392265/235165083-85c78123-c489-44f0-9083-122044f5db6b.png)

**Comment by GalensGan** [comment]
[新版本](https://github.com/GalensGan/SendMultipleEmails/releases) 已经修复了这个问题
