### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by RealnodeVpn** [GalensGan/SendMultipleEmails#18]
1、163邮箱开启smtp需要手机绑定，大量163账户不存在那么手机号码去绑定。
2、配置代理，每个邮箱账户指定代理，如提供proxy模式，自动选择绑定代理ip

**Comment by GalensGan** [comment]
你好，非常感谢您的建议。
关于第 1 条，这个软件的技术就是通过 smtp 去发件的，但是不要求你一定使用 163 邮箱，你可以使用其它的邮件，也可以去淘宝购买，几毛一个账号。
关于第 2 条，代理模式在新版本已经支持了，见 [新框架，新动力](https://github.com/GalensGan/SendMultipleEmails/releases/tag/v0.5.3)
