### ISSUE TITLE
希望能增加支持本地Exchange邮箱发送支持

### ISSUE THREAD

**Issue by apple524** [GalensGan/SendMultipleEmails#19]
希望能增加支持本地Exchange邮箱发送支持

**Comment by GalensGan** [comment]
请问这个需求不需要吗，若需要的话，可以更新进去。目前已更新了 v0.5.x 版本，但是不同的收件人，不同的附件功能没有实现

**Comment by GalensGan** [comment]
目前已支持，具体请查看帮助文档。
