### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by superBiuBiuMan** [GalensGan/SendMultipleEmails#2]
一登录就弹出这个提示,然后邮件也发送不了

**Comment by GalensGan** [comment]
@superBiuBiuMan 经复查，在首页界面会报错，出现这个问题的原因可能是你从没有发过邮件，有些数据缺失，导致首页出错了。这个错误应该不会影响发送邮件的，我再仔细测试下。

**Comment by superBiuBiuMan** [comment]
嗯,你可以看下发送的时候报错的,还是会影响发送的,直接卡在已发送0/1这界面,
![image](https://user-images.githubusercontent.com/54466523/155509740-0ec62b25-f938-488f-8ff2-a0a4fc10a2fb.png)
![image](https://user-images.githubusercontent.com/54466523/155509759-051e227d-0dfd-494b-b664-48abf4a10c26.png)

**Comment by GalensGan** [comment]
753ebf17761a970e2d6c748013000dae33f3c14c @superBiuBiuMan 已经修复。是新建用户时，有些数据没有初始化导致的。请下载 v0.4.4 版本使用。
