### ISSUE TITLE
Bug：成功群发一次以后每次群发都只能发一条

### ISSUE THREAD

**Issue by tpian928** [GalensGan/SendMultipleEmails#20]
您好，感谢您制作了如此优秀的软件。
我已经通过该软件成功进行了一次邮件群发，但是今天再次群发时出现了一个问题：无论我是群发10人还是群发20人，只有第一个人能群发成功，之后邮件发送全是失败的。
然而，我第一次群发是群发了40人，全部成功。
感谢。

**Comment by kobe6013** [comment]
我也是这个问题

**Comment by GalensGan** [comment]
请下载最后新版本 0.5.x 使用，新版本重构了，原则上不会出现这个问题了

**Comment by GalensGan** [comment]
这个问题应该是没有重置每日发件量限制导致的，新版本已经修复
