### ISSUE TITLE
请问后端可否发布在IIS上？通过其他IP地址访问前端网址来使用

### ISSUE THREAD

**Issue by YUQIUSANREN** [GalensGan/SendMultipleEmails#22]
请问后端可否发布在IIS上？通过其他IP地址访问前端网址来使用

**Comment by GalensGan** [comment]
可以，请更新到 v0.5.x 版本，这个版本已经完全支持服务器部署，可以查看说明文档 [服务器部署](https://galens.uamazing.cn/posts/2020/2QMK677#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%83%A8%E7%BD%B2)
