### ISSUE TITLE
win11 闪退

### ISSUE THREAD

**Issue by pwnfox** [GalensGan/SendMultipleEmails#24]
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22621 暂缺 Build 22621
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free

**Comment by GalensGan** [comment]
麻烦提供以下几个信息：
1. 你的安装包版本
2. 是否已经安装了所需的环境，参考 [环境要求](https://galens.uamazing.cn/posts/2020/2QMK677#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82)

**Comment by pwnfox** [comment]
![image](https://github.com/GalensGan/SendMultipleEmails/assets/111500026/8bfb3530-c6ab-4491-ad96-635c9912ce32)

**Comment by GalensGan** [comment]
请更新到最新版本试下：[下载链接](https://cloud.uamazing.cn:52443/#s/-hnFna1g)

**Comment by GalensGan** [comment]
这个是由于 asp.dotnet core 没安装，按安装教程安装下环境就可以了
