### ISSUE TITLE
发件失败-提示*根据当前系统时钟或签名文件中的时间戳验证时要求的证书不在有效期内。

### ISSUE THREAD

**Issue by Sin-CS** [GalensGan/SendMultipleEmails#25]
Windows 10 专业版 - 22H2
大约2024年6月中旬开始使用软件，从2024年8月9日无法正常发送，发送失败的提示如下：

An error occurred while attempting to establish an SSL or TLS connection. The server's SSL certificate could not be validated for the following reasons: * The server certificate has the following errors:*根据当前系统时钟或签名文件中的时间戳验证时要求的证书不在有效期内

**Comment by GalensGan** [comment]
这应该是证书过期，可能是程序存在bug，但近期项目正在重构，无法去检查具体原因。
你可以先打开 service 目录中的程序，然后在浏览器中输入 `http://localhost:22345` 在网页上使用

**Comment by Sin-CS** [comment]
> 这应该是证书过期，可能是程序存在bug，但近期项目正在重构，无法去检查具体原因。 你可以先打开 service 目录中的程序，然后在浏览器中输入 `http://localhost:22345` 在网页上使用

在另一台win11的电脑装了最新版本的进行使用也一样出现这个证书过期的情况。service目录中的程序打开后，在浏览器打开localhost的链接显示"找不到与以下网址对应的网页：http://localhost:22345/", HTTP ERROR 404

**Comment by GalensGan** [comment]
请确认下版本，目前最新版本为 v0.8.9.0，若是这个版本，看看目录 `service/wwwroot` 里面是否有内容。新版本可加群获取，github 更新有点慢

**Comment by GalensGan** [comment]
截图显示，是数据库未能正确升级，可删掉 `C:\Users\%username%\AppData\Local\UZonMail` 文件夹，再启动

**Comment by Sin-CS** [comment]
> 请确认下版本，目前最新版本为 v0.8.9.0，若是这个版本，看看目录 `service/wwwroot` 里面是否有内容。新版本可加群获取，github 更新有点慢

目前使用中的版本是0.8.6.0，QQ群昨天尝试申请但是群满员了。。

**Comment by GalensGan** [comment]
> > 请确认下版本，目前最新版本为 v0.8.9.0，若是这个版本，看看目录 `service/wwwroot` 里面是否有内容。新版本可加群获取，github 更新有点慢
> 
> 目前使用中的版本是0.8.6.0，QQ群昨天尝试申请但是群满员了。。

0.8.9.0 放到 release 上了

**Comment by Sin-CS** [comment]
> 截图显示，是数据库未能正确升级，可删掉 `C:\Users\%username%\AppData\Local\UZonMail` 文件夹，再启动

删除后网页端可以正常打开了，目前在尝试看发件是否正常。wwwroot内容如下
![1](https://github.com/user-attachments/assets/a6fa17d9-24f7-4d0c-8145-dc58a7a90935)
![2](https://github.com/user-attachments/assets/d290080d-6ab2-4a2a-a51e-c81028a8e0b0)

**Comment by Sin-CS** [comment]
> > > 请确认下版本，目前最新版本为 v0.8.9.0，若是这个版本，看看目录 `service/wwwroot` 里面是否有内容。新版本可加群获取，github 更新有点慢
> > 
> > 
> > 目前使用中的版本是0.8.6.0，QQ群昨天尝试申请但是群满员了。。
> 
> 0.8.9.0 放到 release 上了

好的，现在去尝试一下，谢谢

**Comment by Sin-CS** [comment]
目前用的0.8.9.0版本的情况下，发件依旧提示证书过期。。
![A](https://github.com/user-attachments/assets/225f1f10-b017-4700-b1f2-190aacfbd814)
![B](https://github.com/user-attachments/assets/1cbaf688-f13f-41e8-8f5d-c5d013aa8b93)

**Comment by GalensGan** [comment]
你这个是发件箱的证书过期了，发件箱的问题，非本软件的问题

**Comment by Sin-CS** [comment]
> 你这个是发件箱的证书过期了，发件箱的问题，非本软件的问题

请问下这个有什么办法能解决吗，在foxmail软件上进行发件是正常的，使用UZonmail才会有发件失败

**Comment by GalensGan** [comment]
我研究下，过几天回复你

**Comment by Sin-CS** [comment]
> 我研究下，过几天回复你

好的，谢谢。
以及foxmail上和Uzonmail的发件箱设置如下
![1A](https://github.com/user-attachments/assets/8d8f0537-d5f0-4d81-bcab-c6a592fa07c5)
![1B](https://github.com/user-attachments/assets/f7e6cfc0-933c-412b-859f-615c8c544b48)

**Comment by Sin-CS** [comment]
近期已更新到0.9.2版本，重新尝试发送后报错如下：

发件箱 ***** 错误。An error occurred while attempting to establish an SSL or TLS connection.

The server's SSL certificate could not be validated for the following reasons:
• The server certificate has the following errors:
  • 根据当前系统时钟或签名文件中的时间戳验证时要求的证书不在有效期内。
  • 吊销功能无法检查证书是否吊销。
  • 由于吊销服务器已脱机，吊销功能无法检查吊销。

**Comment by GalensGan** [comment]
你这个邮局可以使用非 ssl 发件吗

**Comment by Sin-CS** [comment]
> 你这个邮局可以使用非 ssl 发件吗

不清楚，没有尝试过，是要怎么操作进行测试呢？

**Comment by GalensGan** [comment]
> > 我研究下，过几天回复你
> 
> 好的，谢谢。 以及foxmail上和Uzonmail的发件箱设置如下 ![1A](https://private-user-images.githubusercontent.com/178124796/357262384-8d8f0537-d5f0-4d81-bcab-c6a592fa07c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTg2NjksIm5iZiI6MTcyNDk5ODM2OSwicGF0aCI6Ii8xNzgxMjQ3OTYvMzU3MjYyMzg0LThkOGYwNTM3LWQ1ZjAtNGQ4MS1iY2FiLWM2YTU5MmZhMDdjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNjEyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTdhNWY2NWEzMTg4NzgxYTQ5YTc1ZmZjNTY4NjgwYzZkMDIzY2E4ODEyMWQyYTExZjg4YmI2MzM4N2JlNjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QmaUzYOgbVfXwJtp_5JFBcwQX4w-U-lNGjA3cWWHo-g) ![1B](https://private-user-images.githubusercontent.com/178124796/357262387-f7e6cfc0-933c-412b-859f-615c8c544b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTg2NjksIm5iZiI6MTcyNDk5ODM2OSwicGF0aCI6Ii8xNzgxMjQ3OTYvMzU3MjYyMzg3LWY3ZTZjZmMwLTkzM2MtNDEyYi04NTlmLTYxNWM4YzU0NGI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNjEyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTM0ZjQ5YjA5NDQwMzZkYzllMzk5ZmExNmY2YjQxM2Y1Y2IzMDJmZjUxMWRkYjg5NWExZTdhYTRkODg0MTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3WfMvUihb363yYIXbRoH2xtwelSqwc8_-EtnowXJ3xo)

SSL 关掉，可能端口号要变，这个你要查询你的邮局，一般非 ssl 是 25

**Comment by Sin-CS** [comment]
> SSL 关掉，可能端口号要变，这个你要查询你的邮局，一般非 ssl 是 25

![image](https://github.com/user-attachments/assets/1c2c3c85-382d-4426-9b9a-6ede849644f4)
在foxmail关闭了发件服务器处的SSL 端口变成了25，邮件能正常发送，以及另外的邮箱能正常收到

**Comment by GalensGan** [comment]
嗯嗯，你这个要用 ssl 的话，端口是 993，看你发件箱是 465，可能是这个原因导致的。

**Comment by Sin-CS** [comment]
在Uzonmail上进行相同设置后进行发现依旧报错
![image](https://github.com/user-attachments/assets/44c0fdc3-1dfe-4a0a-81bd-ab91e6e59395)
![image](https://github.com/user-attachments/assets/f9860155-8088-4bc7-b7b1-27ec9f9e3b31)

**Comment by Sin-CS** [comment]
Foxmail和其他发邮软件的发送是正常的
刚刚尝试为启用SSL，端口993，也是提示相同的报错

**Comment by GalensGan** [comment]
可以方便借我一个号测试下吗？

**Comment by GalensGan** [comment]
我的邮箱：260827400@qq.com

**Comment by Sin-CS** [comment]
您方便用远程操控来进行测试吗，向日葵之类的

**Comment by GalensGan** [comment]
可能要修改代码，远程的话我调试不方便

**Comment by Sin-CS** [comment]
> 可能要修改代码，远程的话我调试不方便

大概需要多久呢，会影响我这边正在进行的工作吗？

**Comment by GalensGan** [comment]
我晚上开始处理。不会有影响。

**Comment by Sin-CS** [comment]
> 我晚上开始处理。不会有影响。

![image](https://github.com/user-attachments/assets/ec92d435-7a80-4adf-b149-2ea5ec6c9050)
已经发送，麻烦您了   :)

**Comment by GalensGan** [comment]
已经修复，可以下载 [uzon-mail-v0.9.3](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%23v0.9.3) 测试下
无法发送的原因是你的 SSL 证书过期了。
虽然 uzon-mail 已经兼容了，但为了安全，还是建议你更新你的 SSL 证书。

**Comment by Sin-CS** [comment]
> 已经修复，可以下载 [uzon-mail-v0.9.3](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%23v0.9.3) 测试下 无法发送的原因是你的 SSL 证书过期了。 虽然 uzon-mail 已经兼容了，但为了安全，还是建议你更新你的 SSL 证书。

感谢大佬，稍后我下载来试下。以及SSL这个证书是要怎么更新呀，以前没了解过这方面的东西，是邮箱的东西吗？

**Comment by Sin-CS** [comment]
> 已经修复，可以下载 [uzon-mail-v0.9.3](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%23v0.9.3) 测试下 无法发送的原因是你的 SSL 证书过期了。 虽然 uzon-mail 已经兼容了，但为了安全，还是建议你更新你的 SSL 证书。

新版本无法正确启动，删除\AppData\Local\UZonMail 文件夹后重新启动还是相同的情况，如下
![AA](https://github.com/user-attachments/assets/6e1b259a-48a3-4ba1-b004-32b2fd164aaa)
![BB](https://github.com/user-attachments/assets/e4ea12ea-325e-4ab4-a962-c21e7785eabc)
![CC](https://github.com/user-attachments/assets/2e63e665-305f-40da-a1eb-308dde547e83)

**Comment by GalensGan** [comment]
谢谢反馈，这个是由于数据库初始化出了问题，请下载修复版本 [v0.9.3.1](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%230.9.3.1)

**Comment by Sin-CS** [comment]
> 谢谢反馈，这个是由于数据库初始化出了问题，请下载修复版本 [v0.9.3.1](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%230.9.3.1)

更新后发件箱设置了不启用SSL 端口25的情况下我的邮箱可以正常发件了，目前测试下来一切正常，明天开始会投入大量使用继续测试，后续会再进行反馈。
感谢大佬这段时间的修复，问题目前完美解决！

**Comment by GalensGan** [comment]
> > 已经修复，可以下载 [uzon-mail-v0.9.3](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%23v0.9.3) 测试下 无法发送的原因是你的 SSL 证书过期了。 虽然 uzon-mail 已经兼容了，但为了安全，还是建议你更新你的 SSL 证书。
> 
> 感谢大佬，稍后我下载来试下。以及SSL这个证书是要怎么更新呀，以前没了解过这方面的东西，是邮箱的东西吗？

这个是应该要在你的邮局那儿设置，或者是反向代理那儿设置
