### ISSUE TITLE
您好，软件只发文本没有任何问题，但是不能上传附件，是否您服务器已经关闭了这一功能？然后我不会html，用 ai 生成了一份，自己插入了图片，导入模版后图片是不能用的，软件是不支持插入图片吗？

### ISSUE THREAD

**Issue by muyecc** [GalensGan/SendMultipleEmails#26]
您好，软件只发文本没有任何问题，但是不能上传附件，是否您服务器已经关闭了这一功能？然后我不会html，用 ai 生成了一份，自己插入了图片，导入模版后图片是不能用的，软件是不支持插入图片吗？

**Comment by muyecc** [comment]
感谢大佬的软件，附件我不着急用，只是想插入一些图片，期待您答复

**Comment by GalensGan** [comment]
支持插入图片，上传的图片是存在您本机的后端服务中。
如果你是 windows 用户，要插入图片，首先你需要将图片上传到图床，然后在模板里使用 img 标签引用图片就可以。
很多邮件是不让发图片的，这个你需要测试下

**Comment by muyecc** [comment]
哦哦理解了，谢谢！

**Comment by GalensGan** [comment]
从 [v0.9.4](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md) 开始，支持从附件管理中创建分享链接了，将链接通过 img 标签即可在正文中使用。
该功能相当于一个简易的图床。

**Comment by muyecc** [comment]
感谢提醒，今天去试试

**Comment by muyecc** [comment]
> 从 [v0.9.4](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md) 开始，支持从附件管理中创建分享链接了，将链接通过 img 标签即可在正文中使用。 该功能相当于一个简易的图床。 ![image](https://private-user-images.githubusercontent.com/45629076/364328613-d6cdb6b8-0208-4951-b7da-b56c39f5bd73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mjk5MTAsIm5iZiI6MTcyNTUyOTYxMCwicGF0aCI6Ii80NTYyOTA3Ni8zNjQzMjg2MTMtZDZjZGI2YjgtMDIwOC00OTUxLWI3ZGEtYjU2YzM5ZjViZDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA5NDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDc0NDNjNjA5YzM4YjEyZTA1Y2RjMGE3NzFlZmM4MjYwODZkNTg2ZmQ3NGRhMWE4M2I1YmYzZmRjYzQ3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.teEnuTObb7fXl4RxmP_8YxLO-NTxX0rOO1mQfwzHa_0)

再打扰您咨询个问题，我之前一直用 0.5 版本，可以正常用，今天下载了最新版提示这个，然后我又换了几个 0.9 的其他版本，都是这样
<img width="600" alt="21211E03-4908-43bc-80C1-90089BB683AF" src="https://github.com/user-attachments/assets/ed4308b8-aecf-4dc4-b3f1-395e56acf6e3">

**Comment by muyecc** [comment]
> > 从 [v0.9.4](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md) 开始，支持从附件管理中创建分享链接了，将链接通过 img 标签即可在正文中使用。 该功能相当于一个简易的图床。 ![image](https://private-user-images.githubusercontent.com/45629076/364328613-d6cdb6b8-0208-4951-b7da-b56c39f5bd73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mjk5MTAsIm5iZiI6MTcyNTUyOTYxMCwicGF0aCI6Ii80NTYyOTA3Ni8zNjQzMjg2MTMtZDZjZGI2YjgtMDIwOC00OTUxLWI3ZGEtYjU2YzM5ZjViZDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA5NDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZDc0NDNjNjA5YzM4YjEyZTA1Y2RjMGE3NzFlZmM4MjYwODZkNTg2ZmQ3NGRhMWE4M2I1YmYzZmRjYzQ3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.teEnuTObb7fXl4RxmP_8YxLO-NTxX0rOO1mQfwzHa_0)
> 
> 再打扰您咨询个问题，我之前一直用 0.5 版本，可以正常用，今天下载了最新版提示这个，然后我又换了几个 0.9 的其他版本，都是这样 <img alt="21211E03-4908-43bc-80C1-90089BB683AF" width="600" src="https://private-user-images.githubusercontent.com/100332150/364718935-ed4308b8-aecf-4dc4-b3f1-395e56acf6e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mjk5NjYsIm5iZiI6MTcyNTUyOTY2NiwicGF0aCI6Ii8xMDAzMzIxNTAvMzY0NzE4OTM1LWVkNDMwOGI4LWFlY2YtNGRjNC1iM2YxLTM5NWU1NmFjZjZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwOTQ3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjUwZjYzY2IwZTQ0ZDBkM2M0NDE3MjBkOGY4YThkZjMwM2Y0YjM0ODYyMjVhNzE0ZGRjZDlhZWQwNDY4N2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dp0BpYSVEPWSAuujX4SIUnYn4SSm3aHHR1Kvdst1P9w">

没有开代理或者防火墙

**Comment by GalensGan** [comment]
你把 log 目录中的日志发我邮箱，我看看下。260827400@qq.com

**Comment by GalensGan** [comment]
数据库冲突了，请删掉 `C:\Users\%username%\AppData\Local\UZonMail\uzon-mail.db` 这个文件，然后再启动软件
