### ISSUE TITLE
基础设置-发件设置：发件间隔时间设置无效且会自动恢复默认设置

### ISSUE THREAD

**Issue by Sin-CS** [GalensGan/SendMultipleEmails#28]
系统版本：Windows 10 专业版，版本号 22H2
软件版本：0.9.3.2

情况如下，且修改后不退出设置页面的情况下，实际发件间隔依旧是按照5-10秒执行
https://github.com/user-attachments/assets/a94bdc5f-48ce-4934-a05a-dc2f254e597f

**Comment by GalensGan** [comment]
已经修复了，这个是因为前段时间修改设置界面导致。
下载地址：[v0.9.4](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md)
