### ISSUE TITLE
发送邮件进度0，一直卡死，没法任何操作

### ISSUE THREAD

**Issue by RobinsChens** [GalensGan/SendMultipleEmails#29]
发送邮件进度0，一直卡死，没法任何操作

![image](https://github.com/user-attachments/assets/35dd28c3-cb83-4946-94ab-6dac2437cf16)

**Comment by GalensGan** [comment]
这个是什么版本？

**Comment by GalensGan** [comment]
版本 [v0.9.5](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%230.9.5) 优化了进度显示，你这个问题应该解决了
