### ISSUE TITLE
可以分享一下数据的excel示例吗

### ISSUE THREAD

**Issue by hugoot** [GalensGan/SendMultipleEmails#3]
可以分享一下数据的excel示例吗，看不太懂这个网址下的
https://galens.uamazing.cn/2020/2QMK677.html#%E7%99%BB%E9%99%86%E7%95%8C%E9%9D%A2
中描述的excel数据怎么写

**Comment by GalensGan** [comment]
在程序包中的 sample 目录下有具体的数据格式
![image](https://user-images.githubusercontent.com/45629076/159834805-1a396c0d-c7a3-4bcb-8c8c-432a8f0d4da4.png)

**Comment by hugoot** [comment]
好好，找到了，十分感谢~
您的软件十分优秀，没想到回复得这么快




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GalensGan/SendMultipleEmails"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GalensGan/SendMultipleEmails] 可以分享一下数据的excel示例吗 (Issue #3)





 
在程序包中的 sample 目录下有具体的数据格式
