### ISSUE TITLE
程序意外闪退后自动重新发信导致重复发信且无法暂停或取消

### ISSUE THREAD

**Issue by Sin-CS** [GalensGan/SendMultipleEmails#30]
系统版本：Windows 10 专业版，版本号 22H2
软件版本：0.9.4.0

情况如标题，软件界面显示如下：
![AA](https://github.com/user-attachments/assets/164fdd39-21c3-4cd6-8af7-1daf5bed38e1)

**Comment by GalensGan** [comment]
这个应该是统计显示异常，可以点到明细去看下总数，在明细里，做了防止重发处理，以明细里的数量为准。
但这也是一个bug，等我这个版本优化完成后，会同时进行修复

**Comment by GalensGan** [comment]
版本 [v0.9.5](https://cloud.uamazing.cn:52443/#s/-utHpk6w&view=version.md&link=%230.9.5)  已经对此进行了修复
