### ISSUE TITLE
作者你好，软件无法注册新用户

### ISSUE THREAD

**Issue by slslll** [GalensGan/SendMultipleEmails#4]
![Snipaste_2022-03-24_15-17-26](https://user-images.githubusercontent.com/38198381/159862921-0b92e4e9-ca76-4590-a87f-a3d603724812.png)

**Comment by GalensGan** [comment]
谢谢你提交的bug反馈！经查，这是由于用户验证错误导致的，当前版本被限制为只能用 admin 登陆。下个版本会进行修复。

**Comment by GalensGan** [comment]
已修复 753ebf17761a970e2d6c748013000dae33f3c14c，请重新下载 v0.4.4 版本。

**Comment by slslll** [comment]
作者速度真快👍

> 已修复 [33f0330](https://github.com/GalensGan/SendMultipleEmails/commit/33f0330f7297ab0594f6245fe8734b62bfdf7d57)，请重新下载 v0.4.4 版本。
