### ISSUE TITLE
手动填入收件人后报错

### ISSUE THREAD

**Issue by slslll** [GalensGan/SendMultipleEmails#5]
![Snipaste_2022-04-03_09-51-26](https://user-images.githubusercontent.com/38198381/161407842-e706eab3-575a-4052-81c3-3a734a3f5286.png)

**Comment by GalensGan** [comment]
你的界面好像不对，右侧应该有个选择框。收件人不能输入，要通过选择

**Comment by GalensGan** [comment]
由于软件开发时就是面向多对多发件，所以发件人要现在发件箱中先录入，收件人要现在收件箱那儿先录入，或者在Excel数据中指定

**Comment by slslll** [comment]
明白了，好的
