### ISSUE TITLE
在发件界面选择收件人时，勾选整个收件箱，里面的收件人不会被同时勾选

### ISSUE THREAD

**Issue by slslll** [GalensGan/SendMultipleEmails#6]
![Snipaste_2022-04-04_18-28-35](https://user-images.githubusercontent.com/38198381/161525801-fb78acdc-70c0-4400-902c-a3e19cd2f7df.png)

**Comment by GalensGan** [comment]
谢谢你的反馈，这个是显示没处理好，单功能是和你所需要的那样的，选择组后，就是面向组里所有人。

**Comment by slslll** [comment]
明白了😆

**Comment by slslll** [comment]
貌似还是不行，如果像上图那样选择的话会报这个错误

> ![Snipaste_2022-04-04_18-28-35](https://user-images.githubusercontent.com/38198381/161525801-fb78acdc-70c0-4400-902c-a3e19cd2f7df.png)

**Comment by GalensGan** [comment]
好的，我修复一下

**Comment by GalensGan** [comment]
关于收件人选择组后报错问题，已经修复 4565be0e3eb1d9b36a680533b90cf6a631bc8c99，请下载 v0.4.5 版本使用。

**Comment by slslll** [comment]
谢谢，辛苦了

**Comment by slslll** [comment]
貌似这个问题还没有被修复😅

> ![Snipaste_2022-04-04_18-28-35](https://user-images.githubusercontent.com/38198381/161525801-fb78acdc-70c0-4400-902c-a3e19cd2f7df.png)

**Comment by GalensGan** [comment]
是的，这个逻辑不太好处理，我后面有时间了修复。选择组，是按组发送的。

**Comment by slslll** [comment]
但我如图选择了组之后
> ![Snipaste_2022-04-04_18-28-35](https://user-images.githubusercontent.com/38198381/161525801-fb78acdc-70c0-4400-902c-a3e19cd2f7df.png)
在发件时报这个错误
![161576795-d4fefd22-44ad-4b8d-be67-5a54c5c0a670](https://user-images.githubusercontent.com/38198381/162356615-6c1df0e7-0c7e-442c-a880-07c24fe9329d.png)
是我哪里操作不对吗

**Comment by slslll** [comment]
辛苦了一直麻烦你😉

**Comment by GalensGan** [comment]
不好意思，没注意看消息。收件人和发件人都要选，不能直接输入，你看看是不是这个问题。

**Comment by slslll** [comment]
都有选的，只不过收件人选了整个组（不是直接输入），如图的test，显示的是黄色的图标
而发件人只选了组中的一个，所以是绿色

**Comment by GalensGan** [comment]
你把安装目录里面 log 目录下的日志文件发给我看看

**Comment by slslll** [comment]
[Log.zip](https://github.com/GalensGan/SendMultipleEmails/files/8468610/Log.zip)

**Comment by GalensGan** [comment]
![image](https://user-images.githubusercontent.com/45629076/162855315-f03530d5-d7ca-4e38-899b-de7a89ef137d.png)
刚刚测试了下，没问题，可能是哪儿使用不当我没考虑到。

**Comment by slslll** [comment]
是点发送的时候报的错

**Comment by GalensGan** [comment]
我刚刚是已经发送成功了。你再确认一下是否有选择模板呢？像我图中那样。

**Comment by slslll** [comment]
终于发现问题了，当收件组内的收件箱个数少时可以
目前我有1486个，会报错

**Comment by GalensGan** [comment]
我回头测试下，我查代码，是模板数据为空导致的。

**Comment by slslll** [comment]
好的谢谢，不过我的发件界面唯一和你不一样的就是我的模板没有.html后缀
![Snipaste_2022-04-12_08-58-57](https://user-images.githubusercontent.com/38198381/162857378-2c28b388-3904-4a55-83b8-7a5e12a1a0bb.png)

**Comment by GalensGan** [comment]
那没关系，那个仅是一个名称。
我刚刚用 1486 条数据测试了，也没问题。难以复现啊-_-！

**Comment by slslll** [comment]
又发现一个东西，可能是这个的问题
我用excel批量导入的收件人的时候，excel文件中的姓名栏目都为空，这样是可以导入的（但是发现手动新建收件人，姓名不能为空）
这导致了收件箱现在是这样的
![Snipaste_2022-04-12_09-13-30](https://user-images.githubusercontent.com/38198381/162859241-490cef33-3ba2-4776-b57b-502368a1ebaf.png)
如果确实是这和原因，希望可以支持 空收件人名字😅

**Comment by GalensGan** [comment]
[v0.5.x](https://github.com/GalensGan/SendMultipleEmails/releases/tag/v0.5.3) 版本已经不和名称关联了，而是和邮箱关联，你的问题终于可以解决了

**Comment by slslll** [comment]
爷爷您关注的软件更新啦，感谢开发者！
