### ISSUE TITLE
收件箱中条目多时会造成卡顿

### ISSUE THREAD

**Issue by slslll** [GalensGan/SendMultipleEmails#7]
![Snipaste_2022-04-04_18-29-58](https://user-images.githubusercontent.com/38198381/161526042-45f766b7-de81-46e4-adfd-7e657eea0572.png)
目前5000+条，会造成操作的卡顿

**Comment by GalensGan** [comment]
好，我测试下。发件开始时卡顿是由于为了实现预览，会先生成所有邮件内容，从而导致卡顿，后面我想想用其他方法实现。

**Comment by slslll** [comment]
嗯好的谢谢，这个是在收件箱中操作时会卡顿

**Comment by GalensGan** [comment]
好，当时没考虑到这么大的体量，我优化

**Comment by GalensGan** [comment]
已修复 7a0c5600535bd3b87739965d25510c7358fe4330，请下载 v0.4.5 版本使用
