### ISSUE TITLE
发件组添加多个邮箱时

### ISSUE THREAD

**Issue by keithchi** [GalensGan/SendMultipleEmails#8]
发件组添加多个邮箱时，选择最后一个邮箱，但是实际用于发送的邮箱是倒数第二个
还有我添加了2个分组，第一个分组3个邮箱 第二个分组1个邮箱
发件的时候我选择了第二个组的邮箱，但是实际用于发送的邮箱变成了第一组的第一个邮箱

**Comment by GalensGan** [comment]
谢谢你的反馈，我去复查一下。

**Comment by GalensGan** [comment]
已修复 b439cbf11869ab0892f9dbf7bddea261cd5660e2，请下载 v0.4.5 版本使用
