### ISSUE TITLE
0.4.5版本在多个界面出现Request failed with status code 404

### ISSUE THREAD

**Issue by slslll** [GalensGan/SendMultipleEmails#9]
出现问题的地方有发件箱、收件箱、发件历史
其中，收件箱和发件箱用excel导入或手动新建后，切换到其他地方再重新切换回收件箱或发件箱，其中的内容均无法显示
![Snipaste_2022-04-08_08-57-37](https://user-images.githubusercontent.com/38198381/162342938-cbea7407-35db-4ce6-836a-d46bac40d837.png)
![Snipaste_2022-04-08_08-58-26](https://user-images.githubusercontent.com/38198381/162342942-766f2388-4651-4211-a560-6acce90cc78d.png)
![Snipaste_2022-04-08_08-58-50](https://user-images.githubusercontent.com/38198381/162342944-b4c89f92-341e-4570-ae56-fa7f86ab506e.png)

**Comment by GalensGan** [comment]
打包时，把编译文件弄错了。现已经重新上传，[下载链接](https://github.com/GalensGan/SendMultipleEmails/releases/download/v0.4.5/SendMultipleEmails-v0.4.5.7z)
